version: 2
updates:
  - package-ecosystem: "github-actions" # Monitor GitHub Actions dependencies
    directory: "/"
    schedule:
      interval: "daily" # Check for updates daily

  - package-ecosystem: "cmake" # Monitor CMake dependencies
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates weekly

  - package-ecosystem: "pip" # Monitor Python dependencies (if applicable)
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # Monitor Node.js dependencies (if applicable)
    directory: "/"
    schedule:
      interval: "weekly"
